setup: scan

epochs: 10
batch_size: 512
neighbor_prefix: scatnet_both
neighbor_prefix_val: scatnet_both
train_split: both
val_split: both 

train_method: scan

# Weight update
update_cluster_head_only: True 
num_heads: 10

# Model
backbone: scatnet
model_type: clusterHeads
hidden_dim: 4096
feature_dim: 128 

dataset_type: scan
train_db_name: stl-10
val_db_name: stl-10

num_classes: 10
num_neighbors: 20
to_augmented_dataset: False 
to_neighbors_dataset: True

augmentation_type: twist 
augmentation_strategy: barlow

augmentation_kwargs: 
    local_crops_number: 0 
#   crop_size: 96
#   normalize:
#      mean: [0.485, 0.456, 0.406]
#      std: [0.229, 0.224, 0.225]
#   num_strong_augs: 4
#   cutout_kwargs:
#     n_holes: 1
#     length: 32
#     random: True
    color_jitter: 0.4 
    img_size: 96
    global_crops_scale: [0.4, 1.0]
    local_crops_scale: [0.05, 0.4]
    local_crops_size: 32

transformation_kwargs: 
   crop_size: 96
   normalize:
      mean: [0.485, 0.456, 0.406]
      std: [0.229, 0.224, 0.225]

# Hyperparameters
#optimizer: adam
#optimizer_kwargs:
#   lr: 0.0001
#   weight_decay: 0.0001

num_workers: 8

# Scheduler
optimizer: sgd
optimizer_kwargs:
   nesterov: False
   weight_decay: 0.0001 
   momentum: 0.9
   lr: 0.4
scheduler: cosine
scheduler_kwargs:
   lr_decay_rate: 0.1

      
scatnet_args: 
    J: 2
    L: 16
    input_size: [96, 96, 3] 
    res_blocks: 30
    out_dim: 128


# softmax over loss function
model_args:
    head_type: mlp
    aug_type: multicrop
    batch_norm: False
    last_batchnorm: False
    last_activation: softmax
    drop_out: -1
    
    
loss_type: scan_loss
entropy_weight: 5.0

loss_args:
    lam1: 0.0
    lam2: 1.0
    tau: 1.0
    EPS: 0.00001