main_settings_scan = {'setup': 'scan', 
'epochs': 10, 
'batch_size': 512, 
'neighbor_prefix': 'scatnet_both', 
'neighbor_prefix_val': 'scatnet', 
'train_split': 'both', 
'val_split': 'train', 
'train_method': 'scan', 
'update_cluster_head_only': True, 
'num_heads': 10, 
'backbone': 'scatnet', 
'model_type': 'clusterHeads', 
'hidden_dim': 4096, 
'feature_dim': 128, 
'dataset_type': 'scan', 
'train_db_name': 'stl-10', 
'val_db_name': 'stl-10', 
'num_classes': 10, 
'num_neighbors': 20, 
'to_augmented_dataset': False, 
'to_neighbors_dataset': True, 
'augmentation_type': 'twist', 
'augmentation_strategy': 'barlow', 
'augmentation_kwargs': {'local_crops_number': 0, 'color_jitter': 0.4, 'img_size': 96, 'global_crops_scale': [0.4, 1.0], 'local_crops_scale': [0.05, 0.4], 'local_crops_size': 32}, 
'transformation_kwargs': {'crop_size': 96, 'normalize': {'mean': [0.485, 0.456, 0.406], 'std': [0.229, 0.224, 0.225]}}, 
'num_workers': 8, 
'optimizer': 'sgd', 
'optimizer_kwargs': {'nesterov': False, 'weight_decay': 0.0001, 'momentum': 0.9, 'lr': 0.4}, 
'scheduler': 'cosine', 
'scheduler_kwargs': {'lr_decay_rate': 0.1}, 
'scatnet_args': {'J': 2, 'L': 16, 'input_size': [96, 96, 3], 'res_blocks': 30, 'out_dim': 128}, 
'model_args': {'head_type': 'mlp', 'aug_type': 'multicrop', 'batch_norm': False, 'last_batchnorm': False, 'last_activation': 'softmax', 'drop_out': -1, 'num_neurons': [128, 128, 10]}, 
'loss_type': 'scan_loss', 
'entropy_weight': 5.0, 
'loss_args': {'lam1': 0.0, 'lam2': 1.0, 'tau': 1.0, 'EPS': 1e-05}, 
'pretext_dir': 'RESULTS/stl-10/pretext', 
'pretext_checkpoint': 'RESULTS/stl-10/pretext/scanEvalTest_checkpoint.pth.tar', 
'pretext_model': 'RESULTS/stl-10/pretext/scanEvalTest_model.pth.tar', 
'topk_neighbors_train_path': 'RESULTS/stl-10/topk/scatnet_both_topk-train-neighbors.npy', 
'topk_neighbors_val_path': 'RESULTS/stl-10/topk/scatnet_topk-val-neighbors.npy', 
'scan_dir': 'RESULTS/stl-10/scan', 
'scan_checkpoint': 'RESULTS/stl-10/scan/scanEvalTest_checkpoint.pth.tar', 
'evaluation_dir': 'RESULTS/stl-10/scan/scanEvalTest_measurements', 
'scan_model': 'RESULTS/stl-10/scan/scanEvalTest_model.pth.tar', 
'selflabel_dir': 'RESULTS/stl-10/selflabel', 
'selflabel_checkpoint': 'RESULTS/stl-10/selflabel/scanEvalTest_checkpoint.pth.tar', 
'selflabel_model': 'RESULTS/stl-10/selflabel/scanEvalTest_model.pth.tar', 
'pretrain_path': '/home/blachm86/backbone_models/scatnet.pth' }

trials_scan = [ { 'backbone': ['clPcl'] ,'pretrain_path': ['backbone_clPcl.pth'], 'feature_dim': [512], 'update_cluster_head_only':[True,False], 'batch_size':[128,256] } ]

session_list_scan = [{ 'backbone': 'clPcl' ,'pretrain_path': 'backbone_clPcl.pth', 'feature_dim': 512, 'update_cluster_head_only': True, 'batch_size': 256, 'save_data': True   },
                     { 'backbone': 'clPcl' ,'pretrain_path': 'backbone_clPcl.pth', 'feature_dim': 512, 'update_cluster_head_only': False, 'batch_size': 256, 'save_data': True  },
                     { 'backbone': 'clPcl' ,'pretrain_path': 'backbone_clPcl.pth', 'feature_dim': 512, 'update_cluster_head_only': True, 'batch_size': 128, 'save_data': False  }, 
                     { 'backbone': 'clPcl' ,'pretrain_path': 'backbone_clPcl.pth', 'feature_dim': 512, 'update_cluster_head_only': False, 'batch_size': 128, 'save_data': False } ]