# setup
setup: multidouble
train_method: double

# Weight update
update_cluster_head_only: False # Update full network in SCAN
num_heads: 1 # Only use one head

# Model
backbone: lightly_resnet18

# Dataset
dataset_type: scan
train_db_name: stl-10
val_db_name: stl-10
split: train  # train+unlabeled
num_classes: 10
num_neighbors: 20
to_augmented_dataset: False
to_neighbors_dataset: True

# Transformations
augmentation_strategy: barlow

augmentation_kwargs:
   crop_size: 96
   normalize:
      mean: [0.485, 0.456, 0.406]
      std: [0.229, 0.224, 0.225]
   num_strong_augs: 4
   cutout_kwargs:
     n_holes: 1
     length: 32
     random: True

transformation_kwargs:
   crop_size: 96
   normalize:
      mean: [0.485, 0.456, 0.406]
      std: [0.229, 0.224, 0.225]

# Hyperparameters
optimizer: adam
optimizer_kwargs:
   lr: 0.0001
   weight_decay: 0.0001
epochs: 100
batch_size: 128
num_workers: 8

# Scheduler
scheduler: constant

twist_augmentation:
    color_jitter: 0.4
    img_size: 96
    global_crops_scale: [0.4, 1.0]
    local_crops_scale: [0.05, 0.4]
    local_crops_number: 4
    local_crops_size: 32
    
    
model_type: mlpHead
hidden_dim: 4096
feature_dim: 512

model_args:
    aug_type: multicrop
    batch_norm: False
    last_batchnorm: True
    last_activation: relu # softmax over loss function
    drop_out: -1
    
    
loss_type: double_loss
entropy_weight: 5.0
loss_args:
    lam1: 0.0
    lam2: 1.0
    tau: 1.0
    EPS: 0.00001
    
train_args:
    device: cuda
    aug: barlow
    local_crops_number: 0
